# Generated by Django 4.0.2 on 2022-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
